name: root101
description: Test web server in flutter
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true